[package]
name = "proton-rs"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "main"
path = "src/bin/main.rs"


[lib]
name = "proton"
path = "src/lib/mod.rs"


[dependencies]
clickhouse = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.196", features = ["derive"] }



[dev-dependencies]
clickhouse = { version = "0.11", features = ["test-util"] }